There are some potential issues when running the validate.py

# 4 coming soon locations are eliminated
